In [1]:
import numpy

In [2]:
# numpy array in 1D and 2D

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [10]:
numpy.array([1,2,3])

array([1, 2, 3])

In [11]:
import numpy as np

In [12]:
my_mat = [[1,2,3],[2,3,4],[3,5,6]]

In [13]:
my_mat


[[1, 2, 3], [2, 3, 4], [3, 5, 6]]

In [14]:
np.array(my_mat)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 5, 6]])

In [15]:
# above is two dimension array

In [18]:
# np.arange([start], [stop])
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
# even no
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [22]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [23]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [25]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [34]:
# space no in row
#divide no into part
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [35]:
# create identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [36]:
np.eye(55)

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [41]:
# create arrays of random number
np.random.rand(3,1)

array([[ 0.45376908],
       [ 0.17245282],
       [ 0.53505338]])

In [44]:
# around zero distribution or in guassian distribution
np.random.randn(2)

array([ 0.26072566, -1.65419085])

In [45]:
np.random.randn(2,3)

array([[-2.59174271, -0.4633769 , -0.66596713],
       [ 0.19681529,  0.41260149,  2.70682077]])

In [46]:
# random int low to high
np.random.randint(2,3)

2

In [47]:
np.random.randint(2,100)

99

In [48]:
np.random.randint(2,100)

55

In [49]:
np.random.randint(2,100, 10)

array([19, 44, 23, 39, 24, 20, 13, 63, 80, 82])

In [50]:
#  new methods in array
arr = np.arange(25)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
# same data of new shape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:

arr.max()

24

In [56]:
arr.min()

0

In [57]:
# index location of max value
arr.argmax()

24

In [58]:
# index value of min value
arr.argmin()

0

In [59]:
arr.shape

(25,)

In [61]:
arr.shape

(25,)

In [63]:
arr.dtype

dtype('int64')

In [64]:
# Numpy array index and selection

In [65]:
arr = np.arange(0,11)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
# indexing
arr[8]

8

In [68]:
arr[1:2]

array([1])

In [69]:
arr[:3]

array([0, 1, 2])

In [70]:
arr[0:4]

array([0, 1, 2, 3])

In [71]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [72]:
# in python indexing start from zero

In [73]:
# numpy is different from array because of broadcast
arr[0:4] = 100

In [74]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [75]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [76]:
arr = np.arange(0,11)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
slice_of_array = arr[0:6]

In [79]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [80]:
slice_of_array[:] = 99

In [81]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [82]:
arr_copy = arr.copy()
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [85]:
arr_copy[:] = 100

In [86]:
arr_copy


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [87]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [88]:
arr_2d = np.array([[1,2,3],[20,30,40],[34,22,44]])

In [89]:
arr_2d

array([[ 1,  2,  3],
       [20, 30, 40],
       [34, 22, 44]])

In [90]:
# grabbing elements from 2D array 

In [91]:
# 1st row and in 1st column
arr_2d[0][0]

1

In [92]:
arr_2d[0]

array([1, 2, 3])

In [93]:
arr_2d[1][2]

40

In [94]:
# grab multiple values
arr_2d[:2,1:]

array([[ 2,  3],
       [30, 40]])

In [95]:
arr_2d

array([[ 1,  2,  3],
       [20, 30, 40],
       [34, 22, 44]])

In [96]:
arr_2d[:]

array([[ 1,  2,  3],
       [20, 30, 40],
       [34, 22, 44]])

In [97]:
arr_2d[:2]

array([[ 1,  2,  3],
       [20, 30, 40]])

In [98]:
arr_2d[1:]

array([[20, 30, 40],
       [34, 22, 44]])

In [99]:
arr = np.arange(1,11)

In [100]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
# == operator

In [102]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [103]:
arr <6

array([ True,  True,  True,  True,  True, False, False, False, False, False], dtype=bool)

In [104]:
bool_array = arr> 6

In [105]:
bool_array


array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [106]:
# get only boolean true values
arr[bool_array]

array([ 7,  8,  9, 10])

In [107]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [108]:
arr[arr<3]

array([1, 2])

In [109]:
arr_2d = np.arange(50).reshape(5,10)

In [110]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [111]:
arr_2d[:2,3:]

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19]])

In [112]:
# NUMPY OPERATIONS


In [113]:
arr = np.arange(0,11)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [116]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [117]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [118]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [120]:
arr / arr

/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [121]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr - 0


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
arr / arr

/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [126]:
# in numpy arr/0 = NaN

In [127]:
1 / arr

/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [128]:
# 1 / arr = infinity

In [129]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [131]:
arr **4

array([    0,     1,    16,    81,   256,   625,  1296,  2401,  4096,
        6561, 10000])

In [132]:
# Universal array functions
# see docs more

In [133]:
# square root
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [135]:
# exponention
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [136]:
arr.max()

10

In [137]:
# Trignometry functions
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [138]:
# log

In [139]:
np.log(arr)

/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])