In [1]:
import numpy

In [2]:
# numpy array in 1D and 2D

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [10]:
numpy.array([1,2,3])

array([1, 2, 3])

In [11]:
import numpy as np

In [12]:
my_mat = [[1,2,3],[2,3,4],[3,5,6]]

In [13]:
my_mat


[[1, 2, 3], [2, 3, 4], [3, 5, 6]]

In [14]:
np.array(my_mat)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 5, 6]])

In [15]:
# above is two dimension array

In [18]:
# np.arange([start], [stop])
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
# even no
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [22]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [23]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [25]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [34]:
# space no in row
#divide no into part
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [35]:
# create identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [36]:
np.eye(55)

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [41]:
# create arrays of random number
np.random.rand(3,1)

array([[ 0.45376908],
       [ 0.17245282],
       [ 0.53505338]])

In [44]:
# around zero distribution or in guassian distribution
np.random.randn(2)

array([ 0.26072566, -1.65419085])

In [45]:
np.random.randn(2,3)

array([[-2.59174271, -0.4633769 , -0.66596713],
       [ 0.19681529,  0.41260149,  2.70682077]])

In [46]:
# random int low to high
np.random.randint(2,3)

2

In [47]:
np.random.randint(2,100)

99

In [48]:
np.random.randint(2,100)

55

In [49]:
np.random.randint(2,100, 10)

array([19, 44, 23, 39, 24, 20, 13, 63, 80, 82])

In [50]:
#  new methods in array
arr = np.arange(25)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
# same data of new shape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])